server:
  port: 8415
  servlet:
    context-path: /api/comment
spring:
  application:
    name: search-line-comment-service
  config:
    import: classpath:config.yml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# MyBatis??
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #  type-aliases-package: com.search.entity
  configuration:
    map-underscore-to-camel-case: true