server:
  port: 8214
spring:
  # Elasticsearch??
  elasticsearch:
    uris:
      - http://${search-line.base.zzy}:9200
      - http://${search-line.base.dell}:9200
      - http://${search-line.base.diy}:9200
  application:
    name: search-line-es-core-service
  config:
    import: classpath:config.yml
# MyBatis??
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.search.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    org.elasticsearch.client: DEBUG
    org.springframework.data.elasticsearch.core: DEBUG