<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>top.boking</groupId>
        <artifactId>line-common</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <artifactId>search-line-mq</artifactId>
    <packaging>jar</packaging>
    <name>search-line-mq</name>
    <url>http://maven.apache.org</url>
    <dependencies>
        <!-- RocketMQ依赖 -->
        <dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-spring-boot-starter</artifactId>
            <version>2.3.0</version>
        </dependency>
        <dependency>
            <groupId>top.boking</groupId>
            <artifactId>line-base</artifactId>
        </dependency>


        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
