server:
  port: 8214
spring:
  # MySQL??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.101.167.248:3306/search_line?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

  # Elasticsearch??
  elasticsearch:
    uris:
      - http://192.168.40.95:9200
      - http://192.168.40.95:9201
      - http://192.168.40.95:9202
  # RocketMQ??
  rocketmq:
    name-server: 192.168.18.124:9876
    producer:
      group: search-life-producer
  application:
    name: search-line-es-core-service
  config:
    import: classpath:config.yml

# MyBatis??
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.search.entity
  configuration:
    map-underscore-to-camel-case: true