server:
  port: 8214
spring:
  # Elasticsearch??
  elasticsearch:
    uris:
      - http://192.168.40.95:9200
      - http://192.168.40.95:9201
      - http://192.168.40.95:9202
  application:
    name: search-line-es-core-service
  config:
    import: classpath:config.yml
# MyBatis??
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.search.entity
  configuration:
    map-underscore-to-camel-case: true