spring:
  config:
    import: nacos:${spring.application.name},nacos:config.yml
  cloud:
    nacos:
      discovery:
        ip: 2.0.20.29
        server-addr: 192.168.40.95:8848
        namespace: 20250215
      config:
        server-addr: 192.168.40.95:8848
        namespace: 20250215
        file-extension: properties
        name: ${spring.application.name}
        import-check:
          enabled: false
