search-line:
  base:
    mac: 172.16.126.156
    zzy: 192.168.42.106
    dell: 192.168.42.234
    diy: 192.168.40.95
spring:
  config:
    import: nacos:${spring.application.name},nacos:config.yml
  cloud:
    nacos:
      discovery:
        ip: 2.0.20.154
        server-addr: ${search-line.base.dell}:8848
        namespace: 20250215
      config:
        server-addr: 192.168.42.234:8848
        namespace: 20250215
        file-extension: properties
        name: ${spring.application.name}
        import-check:
          enabled: false
  data:
    redis:
      host: 2.0.20.33
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.101.167.248:3306/search_line?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    redisson:
      config: |
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          subscriptionsPerConnection: 5
          clientName: null
          address: "redis://${search-line.base.mac}:6379"
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 24
          connectionPoolSize: 64
          database: 0
          dnsMonitoringInterval: 5000
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.codec.JsonJacksonCodec> {}
        transportMode: "NIO"
jetcache:
  statIntervalMinutes: 1
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson2
  remote:
    default:
      type: redisson
      keyConvertor: fastjson2
      broadcastChannel: ${spring.application.name}
      keyPrefix: ${spring.application.name}
      valueEncoder: java
      valueDecoder: java
      defaultExpireInMillis: 5000
rocketmq:
  name-server: ${search-line.base.diy}:9876
  producer:
    group: file-service-producer-group
    send-message-timeout: 3000
minio:
  endpoint: http://${search-line.base.mac}:9000
  accessKey: mZSyfS3pFLw2rt04alFq
  secretKey: nh0r7DX4VBzs9tQdQx3WWdxqSnkJ0E4ZQUlpkHQT
  bucketName: search-line
management:
  endpoints:
    web:
      exposure:
        include: prometheus