server:
  port: 8216
spring:
  application:
    name: search-line-user-service
  config:
    import: classpath:config.yml

# MyBatis??
mybatis:
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.search.entity
  configuration:
    map-underscore-to-camel-case: true