spring:
  config:
    import: classpath:config.yml
  application:
    name: search-line-file-service
  # MySQL配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.101.167.248:3306/search_line?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 8215
# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.search.entity
#  configuration:
#    map-underscore-to-camel-case: true
rocketmq:
  name-server: 192.168.18.124:9876
  producer:
    group: file-service-producer-group
    send-message-timeout: 3000