spring:
  config:
    import: classpath:config.yml
  application:
    name: search-line-file-service
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 8215
# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.search.entity
#  configuration:
#    map-underscore-to-camel-case: true
rocketmq:
  name-server: 192.168.18.124:9876
  producer:
    group: file-service-producer-group
    send-message-timeout: 3000